#!/usr/bin/python3
import sys

import amulet
import helpers

d = amulet.Deployment()

d.add('elasticsearch')
config = {'cluster-name': 'unique-name'}
d.configure('elasticsearch', config)

helpers.setup_deployment(d)

health = helpers.get_unit_health(d)

cluster_name = health['cluster_name']

if cluster_name != 'unique-name':
    sys.exit("Expected cluster name to be 'unique-name' "
             "but was '{}'.".format(cluster_name))

print("{prog_name} successful.".format(prog_name=sys.argv[0]))
