#!/usr/bin/python3
import json
import requests
import sys

import amulet

import helpers

d = amulet.Deployment()

d.add('elasticsearch', units=3)

helpers.setup_deployment(d)

health = helpers.get_cluster_health(d, wait_for_nodes=6)

if health['number_of_nodes'] != 6:
    sys.exit("Expected 6 nodes in cluster with 3 units deployed, "
             "got {}".format(health['number_of_nodes']))
