#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.
set -eux # -x for verbose logging to juju debug-log

HOME=`dirname $0`
. $HOME/common.sh

juju-log $JUJU_REMOTE_UNIT joined

# Set hostname for rest client
relation-set cluster-name=${CLUSTER_NAME}
relation-set host=${HOST}