#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.

set -eux # -x for verbose logging to juju debug-log

juju-log $JUJU_REMOTE_UNIT modified its settings

juju-log "##############################################################"
juju-log "#        Relationship Advice -     $JUJU_REMOTE_UNIT         #"
juju-log "##############################################################"
juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list