#!/bin/bash
# Adapted from http://www.elasticsearch.org/tutorials/2010/07/01/setting-up-elasticsearch.html

set -eux # -x for verbose logging to juju debug-log
HOME=`dirname $0`
. $HOME/common.sh

juju-log "Check if we've installed elasticsearch before"

if [ ! -f "/opt/elasticsearch-$VERSION/bin/elasticsearch" ]; then
	juju-log "Installing OpenJDK"
	apt-get install -y default-jre-headless wget curl

  juju-log "Downloading elasticsearch"

  # Check if a local copy of the jar exists
  if [ -f $HOME/../files/charm/elasticsearch-$VERSION.tar.gz ]
  then
    juju-log "elasticsearch binary found local,copy to /tmp"
    install -o root -g root -m 0644 $HOME/../files/charm/elasticsearch-$VERSION.tar.gz /tmp/elasticsearch-$VERSION.tar.gz
  else
    # Download and checksum
    juju-log "elasticsearch wrapper binary not found local ... download"
    wget -q -O /tmp/elasticsearch-$VERSION.tar.gz "${DOWNLOADURL}/elasticsearch-$VERSION.tar.gz"
    if [[ $(sha1sum "/tmp/elasticsearch-$VERSION.tar.gz" | cut -d " " -f 1) != ${CHECKSUM} ]]; then
      juju-log --log-level CRITICAL "Checksum of elasticsearch-$VERSION.tar.gz failed"
      exit 1
    fi
  fi

	juju-log "Installing service wrapper"
  if [ -f $HOME/../files/charm/es-wrapper.tar.gz ]
  then
    juju-log "elasticsearch wrapper binary found local"
    install -o root -g root -m 0644 $HOME/../files/charm/es-wrapper.tar.gz /tmp/es-wrapper.tar.gz
   else
    # Download and checksum
    juju-log "elasticsearch wrapper binary not found local ... download"
    wget  -q -O /tmp/es-wrapper.tar.gz "http://github.com/elasticsearch/elasticsearch-servicewrapper/tarball/master"
    if [[ $(md5sum "/tmp/es-wrapper.tar.gz" | cut -d " " -f 1) != ${CHECKSUMWRAPPER} ]]; then
      juju-log --log-level CRITICAL "Checksum of es-wrapper.tar.gz failed"
      exit 1
    fi
  fi
  juju-log "untar elasticsearch"
  cd /opt
  tar xzvf /tmp/elasticsearch-$VERSION.tar.gz
  ln -s elasticsearch-$VERSION elasticsearch
  rm /tmp/elasticsearch-$VERSION.tar.gz
  juju-log "untar elasticsearch service wrapper"
  tar xzvf /tmp/es-wrapper.tar.gz
  rm /tmp/es-wrapper.tar.gz
  mv *servicewrapper*/service elasticsearch/bin/
  rm -Rf *servicewrapper*

  cd /opt/elasticsearch

  juju-log "Setup elasticsearch as a service"
  /opt/elasticsearch/bin/service/elasticsearch install

  juju-log "Update elasticsearch config"
  sed -i "s/<Path to ElasticSearch Home>/\/opt\/elasticsearch/" bin/service/elasticsearch.conf
  sed -i "s/set\.default\.ES_HEAP_SIZE=.*/set.default.ES_HEAP_SIZE=${HEAP_SIZE}/" bin/service/elasticsearch.conf
  sed -i "s/wrapper.app.parameter.1.*/wrapper.app.parameter.1=$BOOTSTRAP_CLASS/" bin/service/elasticsearch.conf
  sed -i "s/# cluster.name:.*/cluster.name: $CLUSTER_NAME/" config/elasticsearch.yml

  # If Amazon install some magic stuff to allow auto-discovery of other ES nodes.
  if [ ! -z "$ACCESS_KEY" ] && [ ! -z "$SECRET_KEY" ]; then
    juju-log "Install elasticsearch aws plugin"
    bin/plugin -install elasticsearch/elasticsearch-cloud-aws/1.4.0 > /dev/null

    juju-log "Update elastisearch config for ec2"
    cat >> config/elasticsearch.yml << EOF
################################ EC2 Discovery ################################

cloud:
  aws:
    access_key: $ACCESS_KEY
    secret_key: $SECRET_KEY
cloud.aws.region: $REGION

discovery:
  type: ec2
EOF
  fi

# install elasticsearch head
/opt/elasticsearch/bin/plugin -install mobz/elasticsearch-head


fi
