#!/bin/sh
# Adapted from http://www.elasticsearch.org/tutorials/2010/07/01/setting-up-elasticsearch.html

VERSION=$(config-get version)
CLUSTER_NAME=$(config-get cluster-name)
ACCESS_KEY=$(config-get access-key)
SECRET_KEY=$(config-get secret-key)

apt-get update && apt-get -y upgrade

juju-log "Check if we've installed elasticsearch before"

if [ ! -f "/opt/elasticsearch-$VERSION/bin/elasticsearch" ]; then
	juju-log "Installing OpenJDK"
	apt-get install -y default-jre-headless wget

  cd /opt

	juju-log "Downloading elasticsearch"
  wget -q "https://github.com/downloads/elasticsearch/elasticsearch/elasticsearch-$VERSION.tar.gz"
  tar xzvf elasticsearch-$VERSION.tar.gz
  ln -s elasticsearch-$VERSION elasticsearch
  rm elasticsearch-$VERSION.tar.gz

	juju-log "Installing service wrapper"
  wget -q http://github.com/elasticsearch/elasticsearch-servicewrapper/tarball/master -O- | tar -xz
  mv *servicewrapper*/service elasticsearch/bin/
  rm -Rf *servicewrapper*

  cd elasticsearch

  juju-log "Setup elasticsearch as a service"
  bin/service/elasticsearch install

  juju-log "Update elasticsearch config"
  sed -i "s/<Path to ElasticSearch Home>/\/opt\/elasticsearch/g" bin/service/elasticsearch.conf
  sed -i "/cluster.name:/ c\cluster.name: $CLUSTER_NAME" config/elasticsearch.yml

  if [ ! -z "$ACCESS_KEY" && ! -z "$SECRET_KEY" ]; then
    juju-log "Install elasticsearch aws plugin"
    bin/plugin -install elasticsearch/elasticsearch-cloud-aws/1.4.0 > /dev/null
  fi
fi
