#!/bin/sh
# Adapted from http://www.elasticsearch.org/tutorials/2010/07/01/setting-up-elasticsearch.html

VERSION=$(config-get version)

apt-get update && apt-get -y upgrade

juju-log "Check if we've installed elasticsearch before"

if [ ! -f "/opt/elasticsearch-$VERSION/bin/elasticsearch" ]; then
	juju-log "Installing OpenJDK"
	apt-get install -y default-jre-headless wget

  cd /opt

	juju-log "Downloading elasticsearch"
  wget "https://github.com/downloads/elasticsearch/elasticsearch/elasticsearch-$VERSION.tar.gz"
  tar xzvf elasticsearch-$VERSION.tar.gz
  ln -s elasticsearch-$VERSION elasticsearch
  rm elasticsearch-$VERSION.tar.gz

	juju-log "Installing service wrapper"
  wget http://github.com/elasticsearch/elasticsearch-servicewrapper/tarball/master -O- | tar -xz
  mv *servicewrapper*/service elasticsearch/bin/
  rm -Rf *servicewrapper*

  juju-log "Setup elasticsearch as a service"
  elasticsearch/bin/service/elasticsearch install

  juju-log "Update elasticsearch config"
  sed -i "s/<Path to ElasticSearch Home>/\/opt\/elasticsearch/g" elasticsearch/bin/service/elasticsearch.conf
fi
