#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

open-port 9200
/opt/elasticsearch/bin/service/elasticsearch start
